version: '3.9'

services:
  geth-bootnode:
    hostname: geth-bootnode
    container_name: geth_bootnode
    env_file:
      - .env
    image: geth-client
    restart: always
    build:
      context: .
      args:
        PRIVATEKEY: ${PRIVATEKEY}
        PASSPHRASE: ${PASSPHRASE}
    command:
      --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --nodiscover
      --ipcdisable
      --verbosity=${VERBOSITY}
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
      --mine
      --miner.etherbase="${ETHERBASE}"
      --unlock="${ETHERBASE}" 
      --password="/root/.ethereum/keystore/passphrase"
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:
    volumes:
      - ./geth_bootnode:/root/.ethereum/geth

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    container_name: geth_rpc_endpoint
    env_file:
      - .env
    image: geth-client
    depends_on:
      - geth-bootnode   
    restart: always 
    command:
      --verbosity=${VERBOSITY}
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,personal,net,debug,txpool"
      --http.corsdomain="*"
      --http.vhosts="*"
      --ws 
      --ws.addr="0.0.0.0"
      --ws.api="eth,web3,personal,net,debug,txpool"
      --ws.origins="*"
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ./geth_rpcnode:/root/.ethereum/geth
networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28